# Generated by Django 4.2.3 on 2023-07-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('periodoIngresso', models.CharField(choices=[('2023/1', '2023/1'), ('2022/2', '2022/2'), ('2022/1', '2022/1'), ('2021/2', '2021/2'), ('2021/1', '2022/1'), ('2020/2', '2020/2'), ('2020/1', '2020/2'), ('2019/2', '2019/2'), ('2019/1', '2019/1'), ('2018/2', '2018/2'), ('2018/1', '2018/1')], max_length=15, verbose_name='Período de Ingresso')),
                ('foto', models.ImageField(upload_to='images/')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=8, verbose_name='RG')),
                ('curso', models.CharField(choices=[('bsi', 'BSI'), ('tads', 'TADS')], max_length=15, verbose_name='Curso')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('texto', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('2023/1', '2023/1'), ('2022/2', '2022/2'), ('2022/1', '2022/1'), ('2021/2', '2021/2'), ('2021/1', '2022/1'), ('2020/2', '2020/2'), ('2020/1', '2020/2'), ('2019/2', '2019/2'), ('2019/1', '2019/1'), ('2018/2', '2018/2'), ('2018/1', '2018/1')], max_length=15)),
                ('aluno', models.ManyToManyField(related_name='turmas', to='alunos.aluno')),
                ('disciplina', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='alunos.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota')),
                ('situacao_aluno', models.CharField(choices=[('Aprovado', 'APROVADO'), ('Reprovado', 'REPROVADO'), ('Matriculado', 'MATRICULADO'), ('Dispensado', 'DISPENSADO'), ('Cancelado', 'CANCELADO')], max_length=15, verbose_name='Situação do Aluno')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.turma')),
            ],
        ),
    ]
