# Generated by Django 4.2.3 on 2023-08-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default=111, max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('BSI', 'BSI'), ('TADS', 'TADS')], default='BSI', max_length=15, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(upload_to='alunos/static/images'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='Test', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(default=222, max_length=8, verbose_name='RG'),
        ),
    ]
