# Generated by Django 4.2.3 on 2023-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_ingresso',
            field=models.DateField(default='2023-02-01', verbose_name='Data de Ingresso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
